build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - source scripts/hero-z-7045-env.sh
  #  - apt-get update && apt-get -y install build-essential bison flex git python3-pip gawk texinfo libgmp-dev libmpfr-dev libmpc-dev swig3.0 libjpeg-dev lsb-core doxygen python-sphinx sox graphicsmagick-libmagick-dev-compat libsdl2-dev libswitch-perl libftdi1-dev u-boot-tools 
  #  - pip3 install -U artifactory twisted prettytable sqlalchemy pyelftools openpyxl xlsxwriter pyyaml numpy
  script: 
    - ./hero-z-7045-builder -A
  artifacts:
    paths:
      - install
      