language: c
sudo: false
cache:
  apt: true

# required packages to install
addons:
  apt:
    packages:
      - build-essential
      - bison
      - flex
      #- git # should already be installed?
      - python3-pip
      - gawk
      - texinfo
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - swig3.0
      - libjpeg-dev
      - lsb-core
      - doxygen
      - python-sphinx
      - sox
      - graphicsmagick-libmagick-dev-compat
      - libsdl2-dev
      - libswitch-perl
      - libftdi1-dev
      - cmake
      - u-boot-tools
      - fakeroot

branches:
  only:
  #- master
  - travis

before_install:
  - git submodule update --init --recursive

stages:
  - setup
  #- test

jobs:
  include:
    - stage: setup
      name: run builder
      script:
        - ./hero-z-7045-builder -A
