language: c
sudo: false
cache:
  apt: true

# required packages to install
addons:
  apt:
    packages:
      - build-essential
      - bison
      - flex
      #- git # should already be installed?
      - python3-pip
      - gawk
      - texinfo
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - swig3.0
      - libjpeg-dev
      - lsb-core
      - doxygen
      - python-sphinx
      - sox
      - graphicsmagick-libmagick-dev-compat
      - libsdl2-dev
      - libswitch-perl
      - libftdi-dev
      - cmake
      - u-boot-tools
      - fakeroot

branches:
  only:
  #- master
  - travis

before_install:
  - git submodule update --init --recursive

stages:
  - setup-source
  - setup-riscv-gcc
  - setup-pulp-sdk
  - setup-arm-gcc
  - setup-linux
  - setup-offload
  - setup-hero-toolchain
  - install
  #- test

jobs:
  include:

    - stage: setup-source
      name: get sources
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -s

    - stage: setup-riscv-gcc
      name: build RISC-V GCC
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -r

    - stage: setup-pulp-sdk
      name: build PULP SDK
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -p

    - stage: setup-arm-gcc
      name: build ARM GCC
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -a

    - stage: setup-arm-gcc
      name: build Linux
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -a

    - stage: setup-offload
      name: build offload framework
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -o

    - stage: setup-hero-toolchain
      name: build HERO toolchain
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -t

    - stage: install
      name: install HERO toolchain
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -i
