language: c
sudo: false
cache:
  apt: true
git:
  submodules: false # We manually initialize submodules in the 'get sources' job.

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

# required packages to install
addons:
  apt:
    packages:
      - build-essential
      - bison
      - flex
      #- git # should already be installed?
      - python3-pip
      - gawk
      - texinfo
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - swig3.0
      - libjpeg-dev
      - lsb-core
      - doxygen
      - python-sphinx
      - sox
      - graphicsmagick-libmagick-dev-compat
      - libsdl2-dev
      - libswitch-perl
      - libftdi-dev
      - cmake
      - u-boot-tools
      - fakeroot
      - pigz

branches:
  only:
  #- master
  - travis

before_install:
  - pip install --user awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws s3 ls s3://travis-build-stages-hero-sdk/$TRAVIS_BUILD_NUMBER.tar.gz && \
    aws s3 cp s3://travis-build-stages-hero-sdk/$TRAVIS_BUILD_NUMBER.tar.gz $HOME/ && \
    tar -xf $HOME/$TRAVIS_BUILD_NUMBER.tar.gz -C $TRAVIS_BUILD_DIR/..

stages:
  - setup-source
  - setup-riscv-gcc-1
  - setup-riscv-gcc-2
  - setup-pulp-sdk
  - setup-arm-gcc
  - setup-linux
  - setup-offload
  - setup-hero-toolchain
  - install
  #- test

jobs:
  include:

    - stage: setup-source
      name: get sources
      script:
        - git submodule update --init --recursive --recommend-shallow
        - .ci/travis-exec-log ./hero-z-7045-builder -s

    - stage: setup-riscv-gcc-1
      name: build RISC-V GCC (part 1)
      env:
        - HERO_TRAVIS_FIRST_PART=true
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -r

    - stage: setup-riscv-gcc-2
      name: build RISC-V GCC (part 2)
      env:
        - HERO_TRAVIS_SECOND_PART=true
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -r

    - stage: setup-pulp-sdk
      name: build PULP SDK
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -p

    - stage: setup-arm-gcc
      name: build ARM GCC
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -a

    - stage: setup-arm-gcc
      name: build Linux
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -a

    - stage: setup-offload
      name: build offload framework
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -o

    - stage: setup-hero-toolchain
      name: build HERO toolchain
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -t

    - stage: install
      name: install HERO toolchain
      script:
        - .ci/travis-exec-log ./hero-z-7045-builder -i
      after_success:
        # Remove build archive on S3.
        - aws s3 rm s3://travis-build-stages-hero-sdk/$TRAVIS_BUILD_NUMBER.tar.gz

after_success:
  # Update build archive on S3.
  - tar -c --use-compress-program=pigz -f $HOME/$TRAVIS_BUILD_NUMBER.tar.gz -C $TRAVIS_BUILD_DIR/.. hero-sdk
  - aws s3 cp $HOME/$TRAVIS_BUILD_NUMBER.tar.gz s3://travis-build-stages-hero-sdk/

after_failure:
  # Replace build archive on S3 with dump of this job.
  - tar -c --use-compress-program=pigz -f $HOME/$TRAVIS_JOB_NUMBER-failed.tar.gz -C $TRAVIS_BUILD_DIR/.. hero-sdk
  - aws s3 cp $HOME/$TRAVIS_JOB_NUMBER-failed.tar.gz s3://travis-build-stages-hero-sdk/
  - aws s3 rm s3://travis-build-stages-hero-sdk/$TRAVIS_BUILD_NUMBER.tar.gz
